##server:
##  port: 9200
##
##spring:
##  application:
##    name: cloudalibaba-consumer-nacos-order9200
##  cloud:
##    nacos:
##      discovery:
##        server-addr: localhost:8848
##  profiles:
##    active: dev
##
###消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
##service-url:
##  nacos-user-service: http://cloudalibaba-provider-payment9100
###  ————————————————
###  版权声明：本文为CSDN博主「巨輪」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
###  原文链接：https://blog.csdn.net/u011863024/article/details/114298282
##
#spring:
#  profiles:
#    active: dev