server:
  port: 2002

spring:
  application:
    name: seata-storage-service2002

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    io:
      seata: info
