server:
  port: 9400

spring:
  application:
    name: cloud-sentinel-9400
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8849
        port: 8719
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade  # 参考地址https://github.com/alibaba/Sentinel/wiki/Dynamic-Rule-Configuration




management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true