server:
  port: 2001

spring:
  application:
    name: service2001

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    alibaba:
#      seata:
#        tx-service-group: defaultaaa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    io:
      seata: info
