server:
  port: 9100

spring:
  application:
    name: cloudalibaba-provider-payment9100

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 6379
        dashboard: http://localhost:8849
